### ISSUE TITLE
Exception: Failed to load XML file

### ISSUE THREAD

**Issue by 2000222** [rjgpinel/muse#1]
Hello, when I am running "'python -m muse.run --env Pick-v0v", I get the error as follows;
```
File "/home/sarah/muse/muse/core/scene.py", line 37, in __init__
    self.model = load_model_from_path(str(model_path))
  File "mujoco_py/cymj.pyx", line 175, in mujoco_py.cymj.load_model_from_path
Exception: Failed to load XML file: /home/sarah/muse/muse/assets/pick_env.xml. mj_loadXML error: b'XML parse error at line 0, column 0:\nFailed to open file\n'
```
So I guess if I need to download the "pick_env.xml" files or the python scripts can generate them ? Wait for the solution...

**Comment by rgpinel** [comment]
Hi,

thank you for your interest in this repository. I have updated the repository with all the assets.

It should work now.
